<a href="https://colab.research.google.com/github/RogerioDDantas/Programacao_Basica-PRIA_2022-/blob/main/LISTA_4_Programaci%C3%B3n_B%C3%A1sica_(PRIA2022).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ALUNO: Rogério Daniel Dantas

Disciplina: Programación Básica_(PRIA2022)

LISTA 4:

RESOLUÇÃO DOS EXERCÍCIOS:

32 - Dadas matrizes numpy bidimensionais semelhantes, como obter uma saída de matriz numpy onde cada elemento é uma soma de elementos das 2 matrizes numpy?


In [1]:
# Resolução Exercício 32
import numpy as np

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

mat = mat1 + mat2

print("Matriz 1 = ", mat1)
print("Matriz 2 = ", mat2)
print("Soma de mat1 + mat2 = ", mat)

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

Matriz 1 =  [[1 2]
 [3 4]]
Matriz 2 =  [[5 6]
 [7 8]]
Soma de mat1 + mat2 =  [[ 6  8]
 [10 12]]


FIM DO PROGRAMA!!!


33 - Dada uma matriz numpy (matriz), como obter uma saída de matriz numpy que seja igual à matriz original multiplicada por um escalar?



In [ ]:
# Resolução Exercício 33
import numpy as np

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

mat = mat1 + mat2

##print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

# A FINALIZAR!

34 - Crie uma função que retorne uma matriz identidade de dimensão N (parâmetro da função).


In [3]:
# Resolução Exercício 34
import numpy as np

def mat_Indentidade(mat):
  matInv = np.linalg.inv(mat)   # Calcula Matriz Inversa
  matInd = np.dot(mat, matInv)  # Calcula a Matriz Indentidade
  print("Matrix A = \n",mat)
  print("\nMatriz A(-1) = \n", matInv)
  print("\nMatriz A * A(-1) = \n", matInd) 

mat_Indentidade(mat)

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

Matrix A = 
 [[ 6  8]
 [10 12]]

Matriz A(-1) = 
 [[-1.5   1.  ]
 [ 1.25 -0.75]]

Matriz A * A(-1) = 
 [[ 1.0000000e+00 -8.8817842e-16]
 [ 0.0000000e+00  1.0000000e+00]]


FIM DO PROGRAMA!!!


35 - Converta uma matriz 1-D em uma matriz 3D.

In [4]:
# Resolução Exercício 35
import numpy as np

mat1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # Matriz de uma dimensão
mat3D = mat1D.reshape(2, 3, 2)  # Converte uma matriz 1D em uma matriz 3D
print(mat3D)
print('Forma da matriz: ', mat3D.shape)

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Forma da matriz:  (2, 3, 2)


FIM DO PROGRAMA!!!


36 - Empilhe 2 matrizes numpy horizontalmente, ou seja, 2 matrizes que têm a mesma primeira dimensão (número de linhas em matrizes 2D).

In [5]:
# Resolução Exercício 36
import numpy as np

matA = np.array([[1, 2], 
                 [3, 4]])
matB = np.array([[5, 6], 
                 [7, 8]])

#matB = np.array([[5, 6], [7, 8],[9, 0]])


print('Matriz A = \n', matA)
print('Matriz B = \n', matB)

if (len(matA) == len(matB)):
  print("Matriz [A B] = \n", np.hstack((matA, matB)))
else:
  print('Matriz não pode ser empilhada na horizontal')
  print('Dimensoes: A = ', len(matA))
  print('Dimensoes: B = ', len(matB))

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

Matriz A = 
 [[1 2]
 [3 4]]
Matriz B = 
 [[5 6]
 [7 8]]
Matriz [A B] = 
 [[1 2 5 6]
 [3 4 7 8]]


FIM DO PROGRAMA!!!


37 - De 2 arrays numpy, extraia os índices nos quais os elementos dos 2 arrays correspondem.

In [7]:
# Resolução Exercício 37
import numpy as np

matA = np.array([[1, 2], 
                 [3, 4]])
matB = np.array([[5, 6], 
                 [7, 8]])
np.array_equal(matA, matB)


#FALTA FINALIZAR

False

38 - Faça uma função que retorne uma sequência de N números igualmente espaçados no intervalo de 0 a 100 (ambos inclusive).

In [9]:
# Resolução Exercício 38
import numpy as np

def retornoNumero(N):
  num = np.arange(0,101,N)
  print(num)

N = int(input("Digite espaçamento de números que inicia para uma sequencia de 0 a 100\n"))
retornoNumero(N)

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

Digite espaçamento de números que inicia para uma sequencia de 0 a 100
3
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


FIM DO PROGRAMA!!!


39 - Calcule a média móvel do tamanho da janela 3, para a matriz 1D fornecida.

Entrada:

> np.random.seed(100)

> Z = np.random.randint(10, tamanho=10)

Resultado:

In [10]:
# Resolução Exercício 39
import numpy as np

N = 3 #Tamanho do filtro de Média Móvel
np.random.seed(100)
Z = np.random.randint(10, size=10)
print('Matriz 1D = ',Z)
print()

for i in range(len(Z)-N+1): #Calcula Média Móvel
  media = np.mean(Z[i:N+i])
  print(Z[i:N+i])
  print('Média da {}ª Amostra de uma Janela {}, com média = {:.2f} \n'.format(i+1,N,media))

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

Matriz 1D =  [8 8 3 7 7 0 4 2 5 2]

[8 8 3]
Média da 1ª Amostra de uma Janela 3, com média = 6.33 

[8 3 7]
Média da 2ª Amostra de uma Janela 3, com média = 6.00 

[3 7 7]
Média da 3ª Amostra de uma Janela 3, com média = 5.67 

[7 7 0]
Média da 4ª Amostra de uma Janela 3, com média = 4.67 

[7 0 4]
Média da 5ª Amostra de uma Janela 3, com média = 3.67 

[0 4 2]
Média da 6ª Amostra de uma Janela 3, com média = 2.00 

[4 2 5]
Média da 7ª Amostra de uma Janela 3, com média = 3.67 

[2 5 2]
Média da 8ª Amostra de uma Janela 3, com média = 3.00 



FIM DO PROGRAMA!!!


40 - Defina uma classe chamada fracao, contendo dois atributos, num e den, inicializados com valores quaisquer. No método de inicialização, os dois parâmeros passados serão armazenados nos respectivos atributos.

In [11]:
# Resolução Exercício 40
class Fracao:
  num = 0   # atributo publico
  den = 0   # atributo publico
  
  def __init__(self, num, den):
      print("Inicializando Fração!")
      self.num = num
      self.den = den
      

fracao1 = Fracao(10,2)

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

Inicializando Fração!


FIM DO PROGRAMA!!!


41 - Considerando a classe *Point* definida a seguir, crie um método **reflect_x** que retorno um novo objeto *Point* que é a reflexão do ponto no eixo $x$. Por exemplo, $Point(3,5).reflect_X()$ retorno o ponto $3,-5).
```
class Point:

    def __init__(self, initX, initY):

        self.x = initX
        self.y = initY

    def getX(self):
        return self.x

    def getY(self):
        return self.y
```

In [12]:
# Resolução Exercício 41
class Point:

  def __init__(self, initX, initY):
    self.x = initX
    self.y = initY

  def getX(self):
    return self.x

  def getY(self):
    return self.y

  def reflect_x (self):
    print('POINT({},{})'.format(self.x,self.y))

P1 = Point(3,5)
P1.reflect_x()

print("\n\nFIM DO PROGRAMA!!!")
## EXERCÍCIO FUNCIONANDO! ##

POINT(3,5)


FIM DO PROGRAMA!!!
